namespace WmMiddleware.ProductReceiving.Models
{
    internal partial class DatabaseAutomatedShippingNotification
    {
        public AutomatedShippingNotification ToAutomatedShippingNotification()
        {
            return new AutomatedShippingNotification
            {
                InterfaceStatus = InterfaceStatus,
                ShipDate = ShipDate,
                ExternalUid = ExternalUID,
                OrderDate = OrderDate,
                OrderType = OrderType,
                BuyerReferenceNumber = BuyerRefNbr,
                FacilityNumber = FacilityNbr,
                ActualFreightCharge = ActualFreightCharge,
                AutomatedShippingNotificationDirection = ASNdirection,
                AutomatedShippingNotificationFacilityNumber = ASNfacilityNbr,
                AutomatedShippingNotificationNumber = ASNnbr,
                BillToCustomerId = BillToCustomerID,
                Bol = BOL,
                CarrierCode = CarrierCode,
                ClientId = ClientID,
                ContainerSequenceNumber = ContainerSeqNbr,
                CustomerPurchaseOrderDate = CustomerPODate,
                CustomerPurchaseOrderReference = CustomerPORef,
                DiscountedFreightCharge = DiscountedFreightCharge,
                EquipmentId = EquipmentID,
                EquipmentType = EquipmentType,
                ExpectedDeliveryDate = ExpectedDeliveryDate,
                HeaderInterfaceUser1 = HeaderInterfaceUser1,
                HeaderInterfaceUser10 = HeaderInterfaceUser10,
                HeaderInterfaceUser2 = HeaderInterfaceUser2,
                HeaderInterfaceUser3 = HeaderInterfaceUser3,
                HeaderInterfaceUser4 = HeaderInterfaceUser4,
                HeaderInterfaceUser5 = HeaderInterfaceUser5,
                HeaderInterfaceUser6 = HeaderInterfaceUser6,
                HeaderInterfaceUser7 = HeaderInterfaceUser7,
                HeaderInterfaceUser8 = HeaderInterfaceUser8,
                HeaderInterfaceUser9 = HeaderInterfaceUser9,
                IdInterfaceShipmentConfirmationHeader = IDInterfaceShipmentConfirmationHeader,
                InsertDate = InsertDate,
                InterfaceErrorText = InterfaceErrorText,
                LoadId = LoadID,
                OrderId = OrderID,
                OrderLadingQuantity = OrderLadingQty,
                OrderPackagingCode = OrderPackagingCode,
                OrderPriority = OrderPriority,
                OrderStatus = OrderStatus,
                OrderWeight = OrderWeight,
                OrderWeightUom = OrderWeightUOM,
                OriginalMeasureType = OriginalMeasType,
                OutboundCarrierCode = OutBoundCarrierCode,
                ProNumber = ProNbr,
                RouteId = RouteID,
                Scac = SCAC,
                Seal1 = Seal1,
                Seal2 = Seal2,
                ShipFromId = ShipFromID,
                ShipLadingQuantity = ShipLadingQty,
                ShipPackagingCode = ShipPackagingCode,
                ShipToCustomerId = ShipToCustomerID,
                ShipWeight = ShipWeight,
                ShipWeightUom = ShipWeightUOM,
                ShipmentId = ShipmentID,
                ShippingTerms = ShippingTerms,
                SoldToCustomerId = SoldToCustomerID,
                Status = Status,
                StopId = StopID,
                TotalChepPalletsShipped = TotalChepPalletsShipped,
                TotalPalletsShipped = TotalPalletsShipped,
                TotalUnitsShipped = TotalUnitsShipped,
                TotalWeightShipped = TotalWeightShipped,
                TrackingNumber = TrackingNumber,
                UpdateDate = UpdateDate,
                UpdatePid = UpdatePID,
                UpdateUserId = UpdateUserID,
                VendorId = VendorID,
                WeightUom = WeightUOM,
            };
        }

        public AutomatedShippingNotificationItem ToAutomatedShippingNotificationItem()
        {
            return new AutomatedShippingNotificationItem
            {
                ActionCode = ActionCode,
                Style = Style,
                Color = Color,
                SeasonYear = SeasonYear,
                Size = Size,
                Sku = SKU,
                Uom = UOM,
                Upc = UPC,
                CartonQuantity = CartonQTY,
                ChildMuId = ChildMUID,
                ChildMuType = ChildMUType,
                DetailSequenceNumber = DetailSeqNbr,
                EachQuantity = EachQty,
                ExpirationDate = ExpDate,
                Height = Height,
                InterfaceUser1 = InterfaceUser1,
                InterfaceUser10 = InterfaceUser10,
                InterfaceUser2 = InterfaceUser2,
                InterfaceUser3 = InterfaceUser3,
                InterfaceUser4 = InterfaceUser4,
                InterfaceUser5 = InterfaceUser5,
                InterfaceUser6 = InterfaceUser6,
                InterfaceUser7 = InterfaceUser7,
                InterfaceUser8 = InterfaceUser8,
                InterfaceUser9 = InterfaceUser9,
                Length = Length,
                LotId = LotID,
                ManufacturingDate = MfgDate,
                NetWeight = NetWeight,
                PalletBlocks = PalletBlocks,
                PalletDimensionUom = PalletDimensionUOM,
                PalletInnerBlocks = PalletInnerBlocks,
                PalletQuantity = PalletQTY,
                PalletTiers = PalletTiers,
                PalletTypeCode = PalletTypeCode,
                PalletVolume = PalletVolume,
                PalletVolumeUom = PalletVolumeUOM,
                PalletWeight = PalletWeight,
                PalletWeightUom = PalletWeightUOM,
                ParentMuId = ParentMUID,
                ParentMuType = ParentMUType,
                SerialNumber = SerialNbr,
                SkuClass = SKUClass,
                SkuDesc = SKUdesc,
                TareWeight = TareWeight,
                UnitsOrdered = UnitsOrdered,
                UnitsShipped = UnitsShipped,
                Weight = Weight,
                Width = Width
            };
        }
    }
}
