//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("© 2016 New Balance. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Dev")]
[assembly: System.Reflection.AssemblyVersion("1.1.3.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.1.3.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "© 2016 New Balance. All rights reserved.";
    
    internal const string AssemblyConfiguration = "Dev";
    
    internal const string AssemblyVersion = "1.1.3.0";
    
    internal const string AssemblyFileVersion = "1.1.3.0";
    
    internal const string AssemblyInformationalVersion = "1.1.3.0";
    
    private ThisAssembly() {
    }
}
